# Generated by Django 6.0.7 on 2026-08-08 16:56

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AperturaCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('f_creacion', models.DateTimeField(auto_now_add=True)),
                ('f_modificacion', models.DateTimeField(blank=True, null=True)),
                ('u_creo_id', models.IntegerField(blank=True, null=True)),
                ('u_modifico_id', models.IntegerField(blank=True, null=True)),
                ('usuario_id', models.IntegerField()),
                ('fecha_apertura', models.DateTimeField(auto_now_add=True)),
                ('monto_apertura', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
            ],
            options={
                'db_table': 'apertura_caja',
                'ordering': ['-fecha_apertura'],
            },
        ),
        migrations.CreateModel(
            name='CierreCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('f_creacion', models.DateTimeField(auto_now_add=True)),
                ('f_modificacion', models.DateTimeField(blank=True, null=True)),
                ('u_creo_id', models.IntegerField(blank=True, null=True)),
                ('u_modifico_id', models.IntegerField(blank=True, null=True)),
                ('usuario_id', models.IntegerField()),
                ('fecha_cierre', models.DateTimeField(auto_now_add=True)),
                ('ventas', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('monto_cierre', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('diferencia', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('apertura', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cierre', to='manager.aperturacaja')),
            ],
            options={
                'db_table': 'cierre_caja',
                'ordering': ['-fecha_cierre'],
            },
        ),
    ]
