# Generated by Django 6.0.4 on 2026-04-23 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentasporpagar',
            name='estado',
            field=models.IntegerField(choices=[(1, 'Pendiente'), (2, 'Parcial'), (3, 'Pagado'), (4, 'Cancelado')], default=1),
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.IntegerField(choices=[(1, 'Entrada Compra'), (2, 'Traslado Entrada'), (3, 'Ajuste Entrada'), (4, 'Devolución Cliente'), (5, 'Cambio Cliente Entrada'), (10, 'Salida Venta'), (11, 'Traslado Salida'), (12, 'Ajuste Salida'), (13, 'Descarte'), (14, 'Devolución Proveedor'), (15, 'Cambio Cliente Salida')])),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=18)),
                ('stock_anterior', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('stock_resultante', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('venta_id', models.IntegerField(blank=True, null=True)),
                ('compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.compras')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='manager.productos')),
                ('traslado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.traslados')),
                ('ubicacion_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_destino', to='manager.ubicaciones')),
                ('ubicacion_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_origen', to='manager.ubicaciones')),
            ],
        ),
    ]
