# Generated by Django 5.2.5 on 2026-04-11 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedorescontactos',
            name='observaciones',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
