# Generated by Django 6.0.4 on 2026-05-03 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_alter_cuentasporpagar_estado_movimientoinventario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compras',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Recepcion', 'En Recepción'), ('Recepcion Parcial', 'Recepción Parcial'), ('Completado', 'Completado'), ('Con Devolucion', 'Con Devolución'), ('Pendiente Resolucion', 'Pendiente Resolución'), ('Cerrada', 'Cerrada'), ('Cancelada', 'Cancelada')], default='Pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='devolucioncompra',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobada', 'Aprobada'), ('Rechazada', 'Rechazada'), ('Completada', 'Completada'), ('Cancelada', 'Cancelada')], default='Pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='devolucioncompra',
            name='observaciones',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
