# Generated by Django 6.0.7 on 2026-08-08 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_aperturacaja_cierrecaja'),
    ]

    operations = [
        migrations.CreateModel(
            name='CajaAC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('f_creacion', models.DateTimeField(auto_now_add=True)),
                ('f_modificacion', models.DateTimeField(blank=True, null=True)),
                ('u_creo_id', models.IntegerField(blank=True, null=True)),
                ('u_modifico_id', models.IntegerField(blank=True, null=True)),
                ('usuario_id', models.IntegerField()),
                ('fecha_apertura', models.DateTimeField(auto_now_add=True)),
                ('monto_apertura', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('monto_cierre', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('ventas', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('diferencia', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
            options={
                'db_table': 'caja',
            },
        ),
        migrations.RemoveField(
            model_name='cierrecaja',
            name='apertura',
        ),
        migrations.DeleteModel(
            name='AperturaCaja',
        ),
        migrations.DeleteModel(
            name='CierreCaja',
        ),
    ]
