# Generated by Django 6.0.5 on 2026-05-14 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0003_alter_compras_estado_alter_devolucioncompra_estado_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Descuento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_delete", models.BooleanField(default=False)),
                ("f_creacion", models.DateTimeField(auto_now_add=True)),
                ("f_modificacion", models.DateTimeField(blank=True, null=True)),
                ("u_creo_id", models.IntegerField(blank=True, null=True)),
                ("u_modifico_id", models.IntegerField(blank=True, null=True)),
                ("nombre", models.CharField(max_length=150)),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("es_cupon", models.BooleanField(default=False)),
                (
                    "codigo",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                ("es_porcentaje", models.BooleanField(default=True)),
                ("valor", models.DecimalField(decimal_places=2, max_digits=10)),
                ("aplicar_productos", models.BooleanField(default=False)),
                ("aplicar_categorias", models.BooleanField(default=False)),
                ("limite_uso", models.IntegerField(blank=True, null=True)),
                ("cantidad_usados", models.IntegerField(default=0)),
                ("fecha_inicio", models.DateTimeField(blank=True, null=True)),
                ("fecha_fin", models.DateTimeField(blank=True, null=True)),
                ("acumulable", models.BooleanField(default=False)),
                ("requiere_codigo", models.BooleanField(default=False)),
                (
                    "categorias",
                    models.ManyToManyField(blank=True, to="manager.categorias"),
                ),
                (
                    "productos",
                    models.ManyToManyField(blank=True, to="manager.productos"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
