# Generated by Django 6.0.7 on 2026-08-08 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_cajaac_remove_cierrecaja_apertura_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cajaac',
            table=None,
        ),
    ]
