# Generated by Django 5.2.8 on 2026-05-17 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_descuento'),
        ('manager', '0004_perfilusuario'),
    ]

    operations = [
    ]
