# Generated by Django 6.0.7 on 2026-08-08 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_alter_cajaac_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='cajaac',
            name='estado',
            field=models.CharField(choices=[('abierta', 'Abierta'), ('cuadre', 'Cuadre'), ('cerrada', 'Cerrada')], default='abierta', max_length=10),
        ),
        migrations.CreateModel(
            name='DetalleCuadreCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denominacion', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_cuadre', to='manager.cajaac')),
            ],
        ),
    ]
