# Generated by Django 6.0.5 on 2026-05-16 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_descuento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ubicaciones',
            name='tipo',
        ),
        migrations.AddField(
            model_name='ubicaciones',
            name='bodega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tiendas', to='manager.ubicaciones'),
        ),
        migrations.AddField(
            model_name='ubicaciones',
            name='es_bodega',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ubicaciones',
            name='es_tienda',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='descuento',
            name='categorias',
            field=models.ManyToManyField(blank=True, null=True, to='manager.categorias'),
        ),
        migrations.AlterField(
            model_name='descuento',
            name='productos',
            field=models.ManyToManyField(blank=True, null=True, to='manager.productos'),
        ),
    ]
