# Generated by Django 6.0.7 on 2026-08-19 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_cajaac_estado_detallecuadrecaja'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='equival_unid',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='productos',
            name='is_master',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ProductosRel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('f_creacion', models.DateTimeField(auto_now_add=True)),
                ('f_modificacion', models.DateTimeField(blank=True, null=True)),
                ('u_creo_id', models.IntegerField(blank=True, null=True)),
                ('u_modifico_id', models.IntegerField(blank=True, null=True)),
                ('producto_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producto_master_rel', to='manager.productos')),
                ('producto_relacionado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producto_relacionado_rel', to='manager.productos')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('producto_master', 'producto_relacionado'), name='unique_producto_rel')],
            },
        ),
    ]
