# Generated by Django 5.2.8 on 2026-05-18 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_merge_0004_descuento_0004_perfilusuario'),
        ('manager', '0005_remove_ubicaciones_tipo_ubicaciones_bodega_and_more'),
    ]

    operations = [
    ]
