# Generated by Django 6.0.5 on 2026-05-20 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_remove_ubicaciones_tipo_ubicaciones_bodega_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='imagen_nombre',
        ),
        migrations.RemoveField(
            model_name='productos',
            name='imagen_url',
        ),
        migrations.CreateModel(
            name='ProductosImagenes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('f_creacion', models.DateTimeField(auto_now_add=True)),
                ('f_modificacion', models.DateTimeField(blank=True, null=True)),
                ('u_creo_id', models.IntegerField(blank=True, null=True)),
                ('u_modifico_id', models.IntegerField(blank=True, null=True)),
                ('imagen_nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('imagen_url', models.CharField(blank=True, max_length=255, null=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes_producto', to='manager.productos')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
