# Generated by Django 6.0.5 on 2026-05-20 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_remove_productos_imagen_nombre_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductosImagenes',
        ),
    ]
