# Generated by Django 6.0.7 on 2026-08-21 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_productos_equival_unid_productos_is_master_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservaInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('f_creacion', models.DateTimeField(auto_now_add=True)),
                ('f_modificacion', models.DateTimeField(blank=True, null=True)),
                ('u_creo_id', models.IntegerField(blank=True, null=True)),
                ('u_modifico_id', models.IntegerField(blank=True, null=True)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=18)),
                ('estado', models.CharField(choices=[('RESERVADA', 'Reservada'), ('CONSUMIDA', 'Consumida'), ('CANCELADA', 'Cancelada')], default='RESERVADA', max_length=20)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas_inventario', to='manager.productos')),
                ('traslado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservas_inventario', to='manager.traslados')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas_inventario', to='manager.ubicaciones')),
                ('venta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservas_inventario', to='manager.ventas')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
