# Generated by Django 6.0.5 on 2026-05-20 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_delete_productosimagenes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductosImagenes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('imagen_url', models.CharField(blank=True, max_length=255, null=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes_producto', to='manager.productos')),
            ],
        ),
    ]
