# Generated by Django 6.0.7 on 2026-08-24 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_reservainventario'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='cod_cliente',
            field=models.CharField(blank=True, max_length=7, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='d_credito',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='departamento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='max_credito',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='municipio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='pais',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
