# Generated by Django 6.0.7 on 2026-08-24 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_clientes_cod_cliente_clientes_d_credito_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='cod_cliente',
            field=models.CharField(max_length=7, unique=True),
        ),
    ]
