# Generated by Django 6.0.5 on 2026-05-23 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_productosimagenes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='descuento',
            old_name='requiere_codigo',
            new_name='es_cantidad',
        ),
        migrations.AddField(
            model_name='descuento',
            name='cantidad_lleva',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='descuento',
            name='cantidad_paga',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='umedidas',
            name='valor',
            field=models.IntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='descuento',
            name='categorias',
        ),
        migrations.RemoveField(
            model_name='descuento',
            name='productos',
        ),
        migrations.AddField(
            model_name='descuento',
            name='categorias',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.categorias'),
        ),
        migrations.AddField(
            model_name='descuento',
            name='productos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.productos'),
        ),
    ]
