# Generated by Codex on 2026-09-07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0009_alter_clientes_cod_cliente"),
    ]

    operations = [
        migrations.CreateModel(
            name="CuentasPorCobrar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_delete", models.BooleanField(default=False)),
                ("f_creacion", models.DateTimeField(auto_now_add=True)),
                ("f_modificacion", models.DateTimeField(blank=True, null=True)),
                ("u_creo_id", models.IntegerField(blank=True, null=True)),
                ("u_modifico_id", models.IntegerField(blank=True, null=True)),
                ("monto_total", models.DecimalField(decimal_places=2, max_digits=18)),
                ("monto_pendiente", models.DecimalField(decimal_places=2, max_digits=18)),
                ("fecha_vencimiento", models.DateTimeField()),
                (
                    "estado",
                    models.IntegerField(
                        choices=[
                            (1, "Pendiente"),
                            (2, "Parcial"),
                            (3, "Pagado"),
                            (4, "Cancelado"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cliente_cuentas_por_cobrar",
                        to="manager.clientes",
                    ),
                ),
                (
                    "venta",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="venta_cuenta_por_cobrar",
                        to="manager.ventas",
                    ),
                ),
            ],
        ),
    ]
