# Generated by Django 6.0.5 on 2026-05-23 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0009_rename_requiere_codigo_descuento_es_cantidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descuento',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
