# Generated by Django 6.0.5 on 2026-05-25 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0010_alter_descuento_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='impuesto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
