# Generated by Django 5.2.8 on 2026-05-24 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_merge_20260518_1306'),
        ('manager', '0010_alter_descuento_valor'),
    ]

    operations = [
    ]
