# Generated by Django 6.0.7 on 2026-09-07 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0010_cuentasporcobrar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='cod_cliente',
            field=models.CharField(blank=True, max_length=7, null=True, unique=True),
        ),
    ]
