# Generated by Codex on 2026-09-07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0011_alter_clientes_cod_cliente"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistroAbonosCobrar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_delete", models.BooleanField(default=False)),
                ("f_creacion", models.DateTimeField(auto_now_add=True)),
                ("f_modificacion", models.DateTimeField(blank=True, null=True)),
                ("u_creo_id", models.IntegerField(blank=True, null=True)),
                ("u_modifico_id", models.IntegerField(blank=True, null=True)),
                ("monto_abonado", models.DecimalField(decimal_places=2, max_digits=18)),
                ("monto_pendiente", models.DecimalField(decimal_places=2, max_digits=18)),
                ("liquidado", models.BooleanField(default=False)),
                (
                    "cuenta_por_cobrar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cuenta_abonos",
                        to="manager.cuentasporcobrar",
                    ),
                ),
            ],
        ),
    ]
