# Generated by Django 5.2.8 on 2026-05-26 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0011_merge_20260523_1836'),
        ('manager', '0011_productos_impuesto'),
    ]

    operations = [
    ]
