# Generated by Django 5.2.8 on 2026-06-02 01:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0012_merge_20260526_1255'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='datos_sat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero_cai', models.CharField(max_length=100)),
                ('rango_inicial', models.IntegerField()),
                ('rango_final', models.IntegerField()),
                ('fecha_de_emision', models.DateTimeField()),
                ('fecha_de_vencimiento', models.DateTimeField()),
                ('estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('creacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuario_creacion_cai', to=settings.AUTH_USER_MODEL)),
                ('id_sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sucursal_cai', to='manager.ubicaciones')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuario_cai', to=settings.AUTH_USER_MODEL)),
                ('modificacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuario_modificacion_cai', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='facturas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=18)),
                ('impuesto_15', models.DecimalField(decimal_places=2, max_digits=18)),
                ('impuesto_18', models.DecimalField(decimal_places=2, max_digits=18)),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=18)),
                ('total', models.DecimalField(decimal_places=2, max_digits=18)),
                ('tipo_pago', models.CharField(max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuario_factura', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='detalles_facturas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=18)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=18)),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=18)),
                ('impuesto_15', models.DecimalField(decimal_places=2, max_digits=18)),
                ('impuesto_18', models.DecimalField(decimal_places=2, max_digits=18)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='producto_factura_detalles', to='manager.productos')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuario_detalle_factura', to=settings.AUTH_USER_MODEL)),
                ('id_factura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='factura_detalles', to='manager.facturas')),
            ],
        ),
        migrations.CreateModel(
            name='facturas_cai',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero_factura', models.IntegerField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_cai', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cai_facturas', to='manager.datos_sat')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuario_factura_cai', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='facturas',
            name='id_factura_cai',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='factura_cai_detalles', to='manager.facturas_cai'),
        ),
        migrations.CreateModel(
            name='tarjetas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('digitos', models.CharField(max_length=4)),
                ('numero_autorizacion', models.CharField(max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_factura', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='factura_tarjetas', to='manager.facturas')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuario_tarjeta', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
