# Generated by Django 6.0.7 on 2026-09-13

from django.db import migrations, models


def copiar_precio_existente(apps, schema_editor):
    Productos = apps.get_model("manager", "Productos")
    Productos.objects.all().update(
        precio_venta_min=models.F("precio_venta"),
        precio_venta_max=models.F("precio_venta"),
    )


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0012_registroabonoscobrar"),
    ]

    operations = [
        migrations.AddField(
            model_name="productos",
            name="precio_venta_min",
            field=models.DecimalField(decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name="productos",
            name="precio_venta_max",
            field=models.DecimalField(decimal_places=2, max_digits=18, null=True),
        ),
        migrations.RunPython(copiar_precio_existente, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="productos",
            name="precio_venta_min",
            field=models.DecimalField(decimal_places=2, max_digits=18),
        ),
        migrations.AlterField(
            model_name="productos",
            name="precio_venta_max",
            field=models.DecimalField(decimal_places=2, max_digits=18),
        ),
    ]
