# Generated by Django 5.2.8 on 2026-06-05 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0013_datos_sat_facturas_detalles_facturas_facturas_cai_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturas',
            name='rtn',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='datos_sat',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='detalles_facturas',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='facturas',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='facturas_cai',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tarjetas',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
