# Generated by Django 5.2.8 on 2026-06-10 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0014_facturas_rtn_alter_datos_sat_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datos_sat',
            name='nombre_cai',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
