# Generated by Django 5.2.8 on 2026-06-15 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0015_datos_sat_nombre_cai'),
    ]

    operations = [
        migrations.AddField(
            model_name='ubicaciones',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
