# Generated by Django 5.2.8 on 2026-06-23 19:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0016_ubicaciones_ubicacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='aperturas_admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apertura_enfectivo', models.DecimalField(decimal_places=2, max_digits=18)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_cajero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuario_apertura_cajero', to=settings.AUTH_USER_MODEL)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuario_apertura_admin', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='turnos_caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apertura', models.DecimalField(decimal_places=2, max_digits=18)),
                ('cierre', models.DecimalField(decimal_places=2, max_digits=18)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_usuario_caja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuario_turno_caja', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
