# Generated by Django 5.2.8 on 2026-06-23 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0017_aperturas_admin_turnos_caja'),
    ]

    operations = [
        migrations.AddField(
            model_name='turnos_caja',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
