# Generated by Django 6.0.7 on 2026-09-19 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0025_devolucioncompradetalle_unidades_hijo'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedores',
            name='saldo',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=18, null=True),
        ),
    ]
