# Generated by Django 6.0.7 on 2026-09-24 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0047_sincronizar_inventario_padre_hijos'),
    ]

    operations = [
        migrations.AddField(
            model_name='cajaac',
            name='cheque_esperado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='cajaac',
            name='cheque_recibido',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='cajaac',
            name='deposito_esperado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='cajaac',
            name='deposito_recibido',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='cajaac',
            name='tarjeta_esperado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='cajaac',
            name='tarjeta_recibido',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
