# Generated by Django 6.0.7 on 2026-09-24 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0048_cajaac_cheque_esperado_cajaac_cheque_recibido_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetiroCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('f_creacion', models.DateTimeField(auto_now_add=True)),
                ('f_modificacion', models.DateTimeField(blank=True, null=True)),
                ('u_creo_id', models.IntegerField(blank=True, null=True)),
                ('u_modifico_id', models.IntegerField(blank=True, null=True)),
                ('cajero_id', models.IntegerField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=12)),
                ('completado_por_id', models.IntegerField(blank=True, null=True)),
                ('fecha_completado', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.CharField(blank=True, default='', max_length=250)),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retiros', to='manager.cajaac')),
            ],
            options={
                'permissions': [('gestionar_retiros_caja', 'Puede solicitar retiros de efectivo de caja')],
            },
        ),
    ]
