# Generated by Django 6.0.7 on 2026-09-24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0049_retirocaja"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notificacion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_active", models.BooleanField(default=True)),
                ("is_delete", models.BooleanField(default=False)),
                ("f_creacion", models.DateTimeField(auto_now_add=True)),
                ("f_modificacion", models.DateTimeField(blank=True, null=True)),
                ("u_creo_id", models.IntegerField(blank=True, null=True)),
                ("u_modifico_id", models.IntegerField(blank=True, null=True)),
                ("para_todos", models.BooleanField(default=False)),
                ("tipo", models.CharField(choices=[("RETIRO_CAJA", "Retiro de caja"), ("SISTEMA", "Sistema")], default="SISTEMA", max_length=20)),
                ("titulo", models.CharField(max_length=120)),
                ("mensaje", models.CharField(blank=True, default="", max_length=300)),
                ("leida", models.BooleanField(default=False)),
                ("retiro_caja", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="notificaciones", to="manager.retirocaja")),
                ("usuario", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="notificaciones", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-f_creacion"]},
        ),
    ]
