# Generated by Django 6.0.7 on 2026-09-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0050_notificacion"),
    ]

    operations = [
        migrations.AddField(
            model_name="cajaac",
            name="retiros_total",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
