# Generated by Django 6.0.7 on 2026-09-25 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0053_notificacion_referencia_alertas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('RETIRO_CAJA', 'Retiro de caja'), ('STOCK_BAJO', 'Stock bajo'), ('VENCIMIENTO', 'Próximo vencimiento'), ('SISTEMA', 'Sistema')], default='SISTEMA', max_length=20),
        ),
    ]
