# Generated by Django 6.0.7 on 2026-10-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0063_suscripcionsistema"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificacion",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("RETIRO_CAJA", "Retiro de caja"),
                    ("STOCK_BAJO", "Stock bajo"),
                    ("VENCIMIENTO", "Próximo vencimiento"),
                    ("CUENTA_COBRAR", "Cuenta por cobrar"),
                    ("CUENTA_PAGAR", "Cuenta por pagar"),
                    ("SUSCRIPCION", "Suscripción"),
                    ("SISTEMA", "Sistema"),
                ],
                default="SISTEMA",
                max_length=20,
            ),
        ),
    ]
